### ISSUE TITLE
Support Hurricane Electric Free DNS

### ISSUE THREAD

**Issue by alama** [leamas/ddupdate#10]
https://dns.he.net/

```
Note: The username is also the hostname. The password is sent using 'password='. This skips HTTP basic auth.
Authentication and Updating using GET
% curl "https://dyn.dns.he.net/nic/update?hostname=dyn.example.com&password=password&myip=192.168.0.1"
% curl "https://dyn.dns.he.net/nic/update?hostname=dyn.example.com&password=password&myip=2001:db8:beef:cafe::1"

Authentication and Updating using a POST
% curl "https://dyn.dns.he.net/nic/update" -d "hostname=dyn.example.com" -d "password=password" -d "myip=192.168.0.1"
% curl "https://dyn.dns.he.net/nic/update" -d "hostname=dyn.example.com" -d "password=password" -d "myip=2001:db8:beef:cafe::1"
```

**Comment by leamas** [comment]
hm... it shouldn't be that complicated, but I have no testcase (I don't want to delegate my domans to he just for this purpose). If I write some code, could you test it?

**Comment by alama** [comment]
Yes

**Comment by leamas** [comment]
OK, a new plugin is available as a sketch on https://paste.fedoraproject.org/paste/yrLDyQnKh0tDr3kzH62tgg
You could just drop it into ~/.local/share/ddupdate/plugins to test

**Comment by leamas** [comment]
HOLD... I see bugs in that one :(

**Comment by leamas** [comment]
New try. The new plugin is available for test in the *he* branch

**Comment by alama** [comment]
Ok, it updates A record
`sudo -u ddupdate /usr/local/bin/ddupdate -H rigginstereotesta.lawarias.srb2.org -s hurricane_electric -a default-web-ip -l warning -v v4`
But AAAA neeeds
`sudo -u ddupdate /usr/local/bin/ddupdate -H rigginstereotest.lawarias.srb2.org -s hurricane_electric -a default-if -l warning -v v6`
yea, `default-web-ip6` does not work
AND I think when using `ip-disabled` need to force curl to use `-4` or `-6` so the web server get the RIGHT address?

**Comment by leamas** [comment]
> AND I think when using ip-disabled need to force curl to use -4 or -6 so the web server get the RIGHT address?

hm... As things stand, you need to use -v6 to actually update a server AAAA record. Without a *-v6,* it defaults to using v4. Is this a problem?

If it is a problem, what should the solution be, given that ddupdate has no way ti understand if a given hostname refers to an A or an AAAA record?

**Comment by leamas** [comment]
> yea, default-web-ip6 does not work

Could you please expand on this? What are the error messages, if any? Do you have an active ipv6 connection doing this?

Please note that  ipv6 addresses are normally not translated, so using default-if seems natural in the ipv6 case.

**Comment by leamas** [comment]
Ping?

**Comment by alama** [comment]
Still here, just busy

**Comment by leamas** [comment]
Closing after adding the plugin to 0.6.0. Looking carefully  at your comments I actually doesn't see anything wrong with the plugin, it's more about the overall ddupdate functionality. Please file new bug(s) if you have any problems.
