### ISSUE TITLE
service_plugin.ip_cache_ttl is a method and should be called.

### ISSUE THREAD

**Issue by crass** [leamas/ddupdate#11]
I've hit this bug on 0.5.3, but appears to still be in master.  service_plugin.ip_cache_ttl should be called to get the value of ip_cache_ttl, otherwise logging throws an error because its expecting an integer not a bound method.

https://github.com/leamas/ddupdate/blob/e8891063ae7ef109e41ac78db6880b3dd7aa1f24/lib/ddupdate/main.py#L436

**Comment by leamas** [comment]
Fixed in a8992f3

**Comment by leamas** [comment]
Thanks for reporting!
