### ISSUE TITLE
Enhancement: freedns.afraid.org: Support arbitrary addresses

### ISSUE THREAD

**Issue by crass** [leamas/ddupdate#13]
Contrary to the comments in the freedns.afraid.org plugin, the service does support overriding the automatic ip detection by appending `&address=<ip4/6 address>` to the update url.

> TIP: You can override automatic IP detection host by appending &address=127.0.0.10 to any update URL (IPv6 addresses are also allowed)

The `if ip:` warning can be removed and before the log call at the end do something like:

```python
if ip:
    update_url += "&address={0}".format(ip)
```

Before this line:
https://github.com/leamas/ddupdate/blob/e8891063ae7ef109e41ac78db6880b3dd7aa1f24/plugins/freedns.py#L64

**Comment by leamas** [comment]
Have you actually checked this? Last time I tried (some months ago) it didn't work?

**Comment by crass** [comment]
I've only checked this using curl and verified that behavior does work as advertised.  I've not checked the code snippet provided.  I might get around to a pull request, if I get some time.

**Comment by leamas** [comment]
OK, fair enough. I'll try to commit these patches shortly - hopefully you can test them.

**Comment by leamas** [comment]
Fixed in [0eee04e]. Would appreciate if you could test.

**Comment by leamas** [comment]
0.6.1 is out with these fixes. 

Thanks for reporting! Closing.
