### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by tpikonen** [leamas/ddupdate#20]
It would be nice to get a new release (and an updated Debian source package) with the latest fixes.

**Comment by leamas** [comment]
yes... thanks for bringing into my TODO-list. Will try to find some time, stay tuned.

**Comment by leamas** [comment]
Under way:  https://mentors.debian.net/package/ddupdate

**Comment by leamas** [comment]
Under way (fedora)
https://bodhi.fedoraproject.org/updates/FEDORA-2019-44913e549c
https://bodhi.fedoraproject.org/updates/FEDORA-2019-499afb9ab9

**Comment by leamas** [comment]
The Debian package is accepted in sid,  fedora is updated in master and f28 , f29 under way.

Thanks for reporting! Closing.

**Comment by leamas** [comment]
Fedora packages in place, closing.
