### ISSUE TITLE
RFE: Use gnome keyring for passwords instead of .netrc

### ISSUE THREAD

**Issue by leamas** [leamas/ddupdate#23]
The modern keyring is a far better place to store passwords in than the netrc file. Probably an opt-in configuration. See secret-tool(1)

**Comment by leamas** [comment]
The python-keyring package seems to provide the right glue

**Comment by mgrandi** [comment]
bump on this, storing passwords in plaintext is not safe, not all dynamic dns services support 'ip update passwords'

**Comment by leamas** [comment]
Agreed. However: ENOTIME. Patches welcome...

**Comment by leamas** [comment]
Fixed in #23. Closing

**Comment by mgrandi** [comment]
i think you mean it was fixed in this commit: https://github.com/leamas/ddupdate/commit/f6c594e7629b983712c56d21f11a07ba2152fee9 

thanks again!
