### ISSUE TITLE
RFE: Support for multiple records in configuration

### ISSUE THREAD

**Issue by mmannerm** [leamas/ddupdate#25]
As per #24, I would in addition suggest to moving YAML configurations, as there is need to support multiple record updates for multiple hostnames or even for same host, but for both IPv4 and IPv6, which may require using two different address plugins.

For backwards compatibility reasons, old configs should be supported, but new configuration format should be preferred if available. Alternatively if YAML is not to liking, and configparser still needs to be used, better parsing logic on embedded maps is required, and support for multiple sections, and each section should be run separately.

**Comment by leamas** [comment]
I hesitate to pull in the YAML dependency, although it's certainly possible. If yaml was supported by core python it would be a no-brainer.

Using different setups for multiple hosts could be handled using separate config files (and separate systemd setups).  Adding new  sections, each of which corresponding to a separate setup might be possible, and is an interesting possibility.

**Comment by jdfalk** [comment]
How would I go about handling multiple domains for a plugin like google domains? it requires a different user/pass for every dns name.

**Comment by leamas** [comment]
Hi... long time, no see

Basically, I know too little to say something specific. That said, it is possible to start several services. The steps (out of the top of my head).

  - Set up the first service as usual, for example using ddupdate-config.  Verify that it works.
  - Move it out of the way: 
    - In  ~/.config/systemd/user: move ddupdate.service and ddupdate.timer to new names like new-service.service etc.
    - Move ~/.config/ddupdate.conf to new name
    - In the .service file: Add a --config-file option to ddupdate so it finds it's  non-default configuration
  - Test the new service using systemctl --user start new-service.service
  - If/when everything is OK, enable new-service.timer 

Then you can add a new service, and after that possibly repeat the procedure above.

I didn't say this was stream-lined, did I?

**Comment by leamas** [comment]
Pushed  some commits in which makes it possible to have multiple configuration sections for different services/hosts. See the last part of CONFIGURATION.md

I have no plans to support this "multi-host" configuration in ddupdate-config. This is s simple tool and should stay that way.  The more complex case with multiple hosts is best handled by manually editing the config files.  However, decent documentation should make this easier.

**Comment by leamas** [comment]
Fixed in 26af4f2, e189bba, c908ac7 and what not. Closing
