### ISSUE TITLE
Rationale to use this instead of ddclient?

### ISSUE THREAD

**Issue by gwerbin** [leamas/ddupdate#26]
The readme says this is an alternative to ddclient, but doesn't provide a reason to switch. It might be a good idea to add a sentence or two explaining why.

You recently got a shoutout on Reddit in [this thread](https://old.reddit.com/r/linux/comments/c8qp4u/interesting_new_packages_mostly_desktop_to_try_in/), so at least a few people (myself included) will be looking for an answer, especially given that dynamic DNS is such a "set-it-and-forget-it" task, and that ddclient has been around for a long time.

**Comment by leamas** [comment]
Fixed in [63dee17]. Thanks for reporting!

That said, I see no reason for users with a working ddclient setup to switch. However, over time the dynamic DNS host providers comes and goes. If you need to switch, using ddupdate might actually be easier than editing the ddclient config file, YMMV.
