### ISSUE TITLE
RFE: Support for desec.io

### ISSUE THREAD

**Issue by umbz** [leamas/ddupdate#36]
Hi, 
can you add plugin for [desec.io](https://desec.io) service?

i will appreciate!

**Comment by leamas** [comment]
Hm... looks like an interesting service. It uses the dyndns2 protocol, so it should basically be possible to use copy-paste-modify  one of the existing clients baed on dyndns2.

But, I'm short of time. We'll see...

EDIT: API: https://desec.readthedocs.io/en/latest/dyndns/configure.html

**Comment by leamas** [comment]
Fixed in 4080de6. Closing
