### ISSUE TITLE
systemd service is enabled for all users and cannot be disabled

### ISSUE THREAD

**Issue by ruedigerkupper** [leamas/ddupdate#45]
I have a dedicated user for running ddupdate. It has the systemd service (ddupdate.timer) enabled as a user unit and that works fine. Now I noticed that for some reason _all_ users have that unit enabled (both ddupdate.service and ddupdate.timer are enabled and started on boot) – even user root.
Trying to diable the unit has no effect: `systemctl --user disable ddupdate.timer` yields no error, but the unit keeps being enabled.
Since non of the other users has a valid ddupdate config file, it does not harm, but it is irritating to see all those failed ddupdate attempts in the system journal.

Is my systemd setup broken, or why is it the unser units cannot be disabled?

**Comment by leamas** [comment]
hm... strange, indeed. What does the following tell us?
  - `systemctl status ddupdate.timer `
  - `systemctl --user status  ddupdate.timer`, running as the dedicated user
  - `systemctl --user status ddupdate.timer`, running as another user (preferably not root)?

**Comment by ruedigerkupper** [comment]
Oh my … turns out I really messed up my systemd. There was a left-over `.wants`-link to `ddupdate.timer` in the system unit tree. This related report put me on track: https://github.com/NixOS/nixpkgs/issues/21460
Sorry, it wasn't your fault. Thanks for reacting so quickly!

**Comment by ruedigerkupper** [comment]
The three calls you mentioned now do what is to be expected (unit is enabled for the dedicated user only).
