### ISSUE TITLE
RFE: Support for opendns.com

### ISSUE THREAD

**Issue by opoplawski** [leamas/ddupdate#46]
Can you please add support for opendns.com?  Thanks

**Comment by opoplawski** [comment]
ddclient.conf:
```
##
## OpenDNS.com account-configuration
##
protocol=dyndns2
use=web, web=myip.dnsomatic.com
ssl=yes
server=updates.opendns.com
login=opendns_username
password='opendns_password'
opendns_network_label
```

**Comment by leamas** [comment]
looks doable... I might have some cycles later this week.

**Comment by leamas** [comment]
... problems. Seems there is no free/evaluation option I can use. Not really prepared to pay for for the pleasure of supporting this.

It's really boilerplate code.  The first step is to check the API using for example curl (brave human souls tends to skip this step) The api is at  https://support.opendns.com/hc/en-us/articles/227986527-FAQ-OpenDNS-Developer-Resourcesto 

After checking the API, list the available plugins using dyndns2 using `grep -l myip= plugins/*`. Pick the one you think matches your API best. Then just copy for example changeip.com to a new one called opendns.py,  adjust the parameters and drop it into  `~/.local/share/ddupdate/plugins`. 

Then:
  - Check if the new plugin is found: _ddupdate --list-services_
  - Run _ddupdate-config_, 
  - Start the debugging using _ddupdate -L debug_.

Sorry to not be able to help

--alec

**Comment by opoplawski** [comment]
No worries.  Ended up using a different client.
