### ISSUE TITLE
RFE: Support for DNS-O-Matic

### ISSUE THREAD

**Issue by ajorg** [leamas/ddupdate#57]
> DNS-O-Matic gives dynamic IP address users a simple way to distribute their IP changes to multiple services with a single update.

It's very cool, if you don't mind letting them store some passwords. I use it to update Google Domains, Tunnelbroker, and OpenDNS, all at the same time.

I've been using DNS-O-Matic for many years and recently I'm looking for a new update client. Their protocol is effectively just DynDNS2. They have [API docs](https://www.dnsomatic.com/docs/api) and [accounts are free](https://www.dnsomatic.com/create/). Given that OpenDNS is no longer free it's possible DNS-O-Matic will follow eventually. Then again I'm sure DNS-O-Matic is super cheap to operate, and OpenDNS depends on it, so maybe it stays free forever.

Here's my `ddclient.conf`:

```ddclient
ssl=yes
protocol=dyndns2
use=web, web=https://myip.dnsomatic.com
server=updates.dnsomatic.com
login=<user>
password='<password>'
all.dnsomatic.com
```

I see from other issues that the recommendation is to look at an existing plugin that's close to the same protocol, so I'm looking into that. I'll also look at their API docs to see if I can make a module for this that's more correct. Low priority for me, but this client looks interesting so I may get it done eventually.

**Comment by leamas** [comment]
You are welcome to make a DNS-O-matic plugin. When it comes to new plugins I basically have a very liberal attitude. They need to pass a basic review, but that's all there is to it.

However, note that the devel branch lately has been enhanced to support multiple host sections. If I understand this correctly, it means that ddupdate can do the same thing as DNS-O-matic: update multiple services in one transaction. Of course, it does so without leaving passwords at any 3-rd party service .

There is some docs in the very end of CONFIGURATION.md.
