### ISSUE TITLE
handle KeyboardInterrupt 's

### ISSUE THREAD

**Issue by atesin** [leamas/ddupdate#68]
if i run some ddupdate command (ddupdate, ddupdate-config, etc) and i regret and press ctrl-c, it prints confuse stack traces, dirtying the console... maybe the pythonic way to exit programs, but not so user fiendly or unix'ish

**Comment by leamas** [comment]
Well... you probably mean keyboard interrupts, right ;)

It is certainly possible to trap the signal. However, doing so would confuse a large number of users out there which are used to how python works. Also, since running ddupdate interactively is more or less a debug or configuration tool it makes sense to provide as much information as possible. After all, using ctrl-C is certainly not a normal use case.

So I tend to think that this issue should be closed as NOT-A-BUG.

**Comment by atesin** [comment]
i agree with you many users are used to see those stacktrace python messages, but i think the least users that install ddupdate are python developers... most are normal linux users, along with administrators, dba's, etc, that install ddupdate mostly for practical reasons and focus on another tasks, and don't understand too much those messages and mostly confuses them

like me for example... i am not a python developer, but a sysadmin that have a home server for personal projects (web apps, arduino, download movies, etc :) )

certainly stack trace could be useful **for developers**, you could reserve it for development purposes (with `-l debug`option for example)

**Comment by leamas** [comment]
This is actually a property of all python scripts, and there are many of them on a modern Linux system. If this should be filed at all, it should thus be filed against the python project.

That said, patches are welcome, but I will not spend any time on this.  I'm leaning to close, either as NOT-A-BUG or WONTFIX

**Comment by atesin** [comment]
i had done this in a python tutorial i did... let me search...
```
# main loop
try:
  # do whatever
except KeyboardInterrupt:
  # ctrl-c pressed, deal with it, exit loop, etc
```
but  maybe will be better to previously check for `-l debug` and as other laguages do, register a handler function with keyboardinterrupt exception/event, and if not leave is as is?? ...  however i don't know how to do it... maybe with threads

EDIT: look at this = https://docs.python.org/3/library/signal.html#signal.SIGINT

**Comment by leamas** [comment]
Obviously, you have some problems approaching this project. Basically, you don't understand how the tools work, and this makes it hard for you to participate.  I have been in this situation many times, and it leaves you with two options: learn the tools, or just skip the project. Filing overall issues like "I need better documentation" is just not fruitful. In open-source contexts the answer you get is "Indeed, why don't you write it?"

If you actually want to participate you need to acquire some basic skills. From the perspective here, I note:
  - This project, like more or less all open-source projects, requires some basic git skills. You just have to fix it, sorry.
  - As a system administrator you know that all systems must be kept updated, and that problems reported against unsupported versions always are rejected with a "Update your system" reply (I hope you are not using Fedora 33 on a customer system)
  - In this project, you need to know some python.
  - For the particular issue here my answer as a maintainer is the common one: patches welcome. That is, if you can provide a Github Pull Request "solving" this issue I'll review and perhaps merge it. But no, I will not spend time on it in any other way. 
 
There is always a need for better docs, examples and what not. However,  there are already ten users actively participating, so it cannot be that bad for a niche project like this.

**Comment by atesin** [comment]
i am updated my system and been hitted against a wall when i wanted to organize my ddns scripts and domains ... i used to use ddclient, but now looking this project, the new kid on the block, it makes look ddclient a little outdated

certainly if i didn't felt the need for update my system (personal, not for customers... for customers we use rhel) everything would still working ok, until sometime things will break

i have not so much spare time now, sorry... i also had to travel for family issues...  but when i finish to update my system (i already upgraded to fedora 36 yesterday, but found worst ddupdate problems) then i will investigate more deeply and hopefully sent you some patches, remember i am not a developer so i will try to learn and do my best
